version: '3.1'

services:
  web:
    image: web
    build:
      context: backend
      dockerfile: backend.Dockerfile
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 8000:8000
    volumes:
      - ./backend:/opt/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: