"""added user model and relationships

Revision ID: 2f0f1e4835f9
Revises: 337ddd64a407
Create Date: 2021-12-18 16:45:49.534335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f0f1e4835f9"
down_revision = "337ddd64a407"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
