"""added username

Revision ID: 99a1574eabaf
Revises: 2f0f1e4835f9
Create Date: 2021-12-23 20:48:39.959071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99a1574eabaf"
down_revision = "2f0f1e4835f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
